[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "22a107e2783e93d37e7aba57097f1dbabfe15da7"
os = "macos"

    [[aws_c_cal.download]]
    sha256 = "8a4a35e17b26f89bd2a6e0304c84183d0b4c0c5ce566a32dcea8e0d7a1ec6c5f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.aarch64-apple-darwin.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "cefed7e9d21b54c62a68660effaf7ce61fef1abe"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "4c6f525913832befe127b7087ec0547aa57601ee5b6faaa0ef36452029c9c823"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.aarch64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "ca4268d9538c9de8800123e60a0ca1c66eed0dab"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "26afa58ada51f0ee01128299a81bb6c089c01a2e2fd49f985942eec99f8b7af3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.aarch64-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "250fdd4d3a8cb181050e2a305db61992822c367f"
os = "freebsd"

    [[aws_c_cal.download]]
    sha256 = "5ebc6c5b9f6e3379659fe4807e2a2d5fd3e3b9ab8083479f64a974241522f9ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.aarch64-unknown-freebsd.tar.gz"
[[aws_c_cal]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36fc09afdd65e17b2c67be9b28999033125a0946"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "cb3d7b2294d72566a00be2bc0dc35a9158f53c170ecae1849eaa225a75f1ba69"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_cal]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a337b94d6c94b41787f47fa83bf519e33812a6cc"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "1effc0188ae1ad3e919e7d702cdf30cf4b10c21773a54b815282eeae27a583ae"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.armv6l-linux-musleabihf.tar.gz"
[[aws_c_cal]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be739af9710fa937b1aadf71fa7305ac4d68c467"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "1a23cd50067cebbcc0c70300c7f0c812b706e051c49723bba2c9e9a1a1ca21a3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_cal]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "357f68e61a2380550947f8aa5ac63d0595a88d86"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "824afab7319668414b497bef429c7a2c05943cea56058ca6408b578c67116c56"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.armv7l-linux-musleabihf.tar.gz"
[[aws_c_cal]]
arch = "i686"
git-tree-sha1 = "876da2a7cb189de43376c382d771800cdca61a26"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "a2742601c886e0a41207cead1a0b61b8e01a7cb813acbbf5ea12dc90a71bd7ff"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.i686-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "i686"
git-tree-sha1 = "a1d460fbe4d31752e9b052019f7f2d3d5d330610"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "834cb0bb81208316444f8923d1bdc78bf3c26589e371269effe485c185db1dfa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.i686-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "powerpc64le"
git-tree-sha1 = "0f5d36147fc7e151f207afe1dfe69ca24a6f9c2b"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "e1e33314a254d6107c8f92e539f29da3e2df2419197fe91db56ce769c0f92dfa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.powerpc64le-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "riscv64"
git-tree-sha1 = "e8ffb9206d8372b608dfb692bc8b2b7616ab5ef7"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "c030900ba7ef81082995e93c7780b4300b2397a0e1f531bcbe3293a31be17040"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.riscv64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "acd65598212b97df4ce1557a82364df04ae4bb5b"
os = "macos"

    [[aws_c_cal.download]]
    sha256 = "76e603b6e1e7c2cbb3146850ee9ccb04dad91e48eba74a16e0302c79f445eb3f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.x86_64-apple-darwin.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "679d7452683283586d8b3c2b34345ce9be0823b3"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "f440e4b46bb01f5c2b86f1d27e3ced38d59601d8c02c0f0555924855e288930f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.x86_64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "80f4982c743249315f4da08b3ef0afc1383e74f5"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "b87d1892165c043fcd870517027097d1a59880f22f7b8118bbfbc2738ca8ce69"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.x86_64-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "a0b2d645cb81dac6a41c1a2e63c15dc70cdd2dbd"
os = "freebsd"

    [[aws_c_cal.download]]
    sha256 = "cfa05feba2d318b5ff8de40b4f88dd2e1cfa4c549a4d11b20459cafe4a182f5a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.x86_64-unknown-freebsd.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "3df1f93ea9bf6c8295f8094f9e4603652a034fff"
os = "windows"

    [[aws_c_cal.download]]
    sha256 = "f284eb87d639414b47fb308d579973596de12cf2a4bd3b38e3d9dad1ee8a5456"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.12+0/aws_c_cal.v0.9.12.x86_64-w64-mingw32.tar.gz"
