[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "e8161ab7dda41ec3d64ed762409d1f984d1c27ce"
os = "macos"

    [[aws_c_cal.download]]
    sha256 = "ee6c8bcd32f085fbc9eb40e73fb1bb1ff44275d1356eb4a1594a2caf3d2b4d13"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.aarch64-apple-darwin.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "cd6cff76511463c694faa35dc0223495a5966034"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "8143d545181b3c40b3dc07c3e0b76f00c6bd62aa60d7c6a990f94cfc924a8d28"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.aarch64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "89c676de72187d041588a3e28591dc67730a7dcb"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "b8a8a05ff549c5338251b97e9e7ba2ebca5a8d22e0b238cd29f47cad78911df8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.aarch64-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "aarch64"
git-tree-sha1 = "bc7b4eca0242e74e4e03adc6787c8db5482b067f"
os = "freebsd"

    [[aws_c_cal.download]]
    sha256 = "2d96800698aa636e4e0d3e9be162a0a47bf5a454db64b13cea72c6b647ffc3f6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.aarch64-unknown-freebsd.tar.gz"
[[aws_c_cal]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6dbe76aa8774119a088eb5af2199e7bda308b199"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "b107c7b23e4b53cacdbd14bb8264fd5815ccc62f09f5a2ec4ee2fc19724f9315"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_cal]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e557dba5ecee5db2517776008fedf81747a2466"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "576abd4c7a7b10ad654c18fbe5eb34127f1351abfcf4071eba4e624007dc0c3f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.armv6l-linux-musleabihf.tar.gz"
[[aws_c_cal]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc49a9c5a34be23f52ab6a93320675662d88986a"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "2385a7707e21e6ab66466e734c7541ed09485b31979fa04c035f7f6f710c8146"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_cal]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc80dcd4bf177743f71e9d9bc90d33e884fe8cac"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "3e602971232da09789754c74315909f64dea6f1330e48053c07b16a7cef5c472"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.armv7l-linux-musleabihf.tar.gz"
[[aws_c_cal]]
arch = "i686"
git-tree-sha1 = "ff01ac61c3e524ba981146bb399e7a256bfbf834"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "8901f2e4ce0bfc603cc99b6e07c1a8d8f7a97c461c1747076be8185137534727"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.i686-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "i686"
git-tree-sha1 = "b742362bd031dbcb2ddbfc94d4bb9cb64c79e95c"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "8260fde2c789e451e17eda86bfe2fe3f6c354ab4605f5e46f6a49be07a906bd7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.i686-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "powerpc64le"
git-tree-sha1 = "4f685e1b1a862a5b81b4746127ffc701253858ea"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "6801b3ec7cadd1922475cf01f2e426776be3c10e64465fb52b3518a8f02832bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.powerpc64le-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "riscv64"
git-tree-sha1 = "fde81a732c56e502dea5656ce398554bd5e25856"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "76e33d6fffff67fb2bc79ea7c2f23aa201fc9a69e7ab2bc56a969f5f1bcf5d89"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.riscv64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "50e4fd1b69332110abd5497d1c1aec018260635e"
os = "macos"

    [[aws_c_cal.download]]
    sha256 = "99928f93937cf283e33de1b47cf18d65519c07147067c0b47e2e13c70e9fdc02"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.x86_64-apple-darwin.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "db95bc31c94ea4134a86c976a4b0fbf7c704daff"
libc = "glibc"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "e64f0b232b90c06cb62bc1de43e3bec5596fcb2496e2d7c1a53ccdbe5c9e9378"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.x86_64-linux-gnu.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "d0a92a3ed9a05e52024d451663e0b595326942d1"
libc = "musl"
os = "linux"

    [[aws_c_cal.download]]
    sha256 = "7ec139f011ba3ae9dfbc62afb1b1d23f6e7dcbfc7654a7f29a28585cb898936d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.x86_64-linux-musl.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "0d5650d2bee563774a8335f116994051e3f64251"
os = "freebsd"

    [[aws_c_cal.download]]
    sha256 = "c7dc5af249580e121c840a26e9653d65172d7a6dcdecd81c74739bf779a603fc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.x86_64-unknown-freebsd.tar.gz"
[[aws_c_cal]]
arch = "x86_64"
git-tree-sha1 = "a6fab5b0b96ad3a4297f597ecf2bd782b9497011"
os = "windows"

    [[aws_c_cal.download]]
    sha256 = "1b6070969d079b41b0fe8d0c4e74fea8202de1be9aa817323bbd171cd7234aaf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_cal_jll.jl/releases/download/aws_c_cal-v0.9.11+0/aws_c_cal.v0.9.11.x86_64-w64-mingw32.tar.gz"
