name = "aws_c_cal_jll"
uuid = "70f11efc-bab2-57f1-b0f3-22aad4e67c4b"
version = "0.9.7+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
aws_c_common_jll = "73048d1d-b8c4-5092-a58d-866c5e8d1e50"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
aws_c_common_jll = "0.12.5"
Artifacts = "< 0.0.1, 1"
